name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Build Docker Image"
        run: docker build -t pweb-backend .

      - name: "Login to docker registry"
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin "${{ secrets.DOCKER_REGISTRY }}:${{ secrets.DOCKER_PORT }}"

      - name: "Tag Docker image with commit SHA"
        run: |
          IMAGE_TAG="${{ secrets.DOCKER_REGISTRY }}:${{ secrets.DOCKER_PORT }}/pweb-backend:$(echo ${GITHUB_SHA::8})"
          docker tag pweb-backend $IMAGE_TAG

      - name: "Push Docker Image To Registry ( with SHA8 tag )"
        run: docker push "${{ secrets.DOCKER_REGISTRY }}:${{ secrets.DOCKER_PORT }}/pweb-backend:$(echo ${GITHUB_SHA::8})"

      - name: "Push Docker Image To Registry ( with latest tag )"
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          docker build -t pweb-backend .
          docker tag pweb-backend "${{ secrets.DOCKER_REGISTRY }}:${{ secrets.DOCKER_PORT }}/pweb-backend:latest"
          docker push "${{ secrets.DOCKER_REGISTRY }}:${{ secrets.DOCKER_PORT }}/pweb-backend:latest"
